name: Chrome Remote Desktop

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit PIN for Chrome Remote Desktop'
        required: true

jobs:
  setup-crd:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Initialize Setup
      shell: pwsh
      run: ./setup.ps1

    - name: Install Chrome Remote Desktop Host
      shell: pwsh
      run: |
        $authCode = "${{ github.event.inputs.authcode }}"
        $pinCode = "${{ github.event.inputs.pincode }}"
        & "C:\Program Files (x86)\Google\Chrome Remote Desktop\remoting_start_host.exe" --code="$authCode" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="GitHubRunner" --pin="$pinCode"

    - name: Keep Alive
      shell: pwsh
      run: ./timeout.ps1
